"use client";

import { useState, FormEvent } from "react";

// Define the type for the form data based on your backend model.
// 'id' is omitted as it should be generated by the database.
export type JobFormData = {
  name: string;
  description: string;
  deadline: string; // The HTML input for datetime-local provides a string
  assignee: string;
  status: string;
  category: string;
};

// Define the props for the modal component
interface CreateJobModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreate: (jobData: JobFormData) => void;
}

const CreateJobModal = ({ isOpen, onClose, onCreate }: CreateJobModalProps) => {
  // Initial state for the form, with default values.
  const initialFormData: JobFormData = {
    name: "",
    description: "",
    deadline: "",
    assignee: "",
    status: "pending", // Default status as per your model
    category: "",
  };

  const [formData, setFormData] = useState<JobFormData>(initialFormData);

  // A generic handler to update the form state.
  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // Handles the form submission.
  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    // Basic validation to ensure the required 'name' field is not empty.
    if (!formData.name.trim()) {
      alert("Job Name is a required field.");
      return;
    }
    onCreate(formData); // Pass the form data to the parent component.
  };

  // Don't render the modal if it's not open.
  if (!isOpen) {
    return null;
  }

  // Common CSS classes for form elements to ensure consistency.
  const labelCssStyles = "block text-sm font-medium text-gray-700 mb-1";
  const inputCssStyles =
    "mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm";

  return (
    // Modal Overlay: covers the entire screen to focus user attention.
    <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex justify-center items-center p-4">
      {/* Modal Content */}
      <div className="bg-white p-6 rounded-lg shadow-xl w-full max-w-md">
        <h2 className="text-2xl font-bold mb-5 text-gray-800">Create a New Job</h2>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4">
            {/* Job Name */}
            <div>
              <label htmlFor="name" className={labelCssStyles}>
                Job Name
              </label>
              <input
                type="text"
                name="name"
                id="name"
                value={formData.name}
                onChange={handleChange}
                required
                className={inputCssStyles}
              />
            </div>

            {/* Description */}
            <div>
              <label htmlFor="description" className={labelCssStyles}>
                Description
              </label>
              <textarea
                name="description"
                id="description"
                value={formData.description}
                onChange={handleChange}
                rows={3}
                className={inputCssStyles}
              />
            </div>

            {/* Deadline */}
            <div>
              <label htmlFor="deadline" className={labelCssStyles}>
                Deadline
              </label>
              <input
                type="datetime-local"
                name="deadline"
                id="deadline"
                value={formData.deadline}
                onChange={handleChange}
                className={inputCssStyles}
              />
            </div>

            {/* Assignee */}
            <div>
              <label htmlFor="assignee" className={labelCssStyles}>
                Assignee
              </label>
              <input
                type="text"
                name="assignee"
                id="assignee"
                value={formData.assignee}
                onChange={handleChange}
                className={inputCssStyles}
              />
            </div>

            {/* Category */}
            <div>
              <label htmlFor="category" className={labelCssStyles}>
                Category
              </label>
              <input
                type="text"
                name="category"
                id="category"
                value={formData.category}
                onChange={handleChange}
                className={inputCssStyles}
              />
            </div>

            {/* Status */}
            <div>
              <label htmlFor="status" className={labelCssStyles}>
                Status
              </label>
              <select
                name="status"
                id="status"
                value={formData.status}
                onChange={handleChange}
                className={inputCssStyles}
              >
                <option value="pending">Pending</option>
                <option value="in-progress">In-Progress</option>
                <option value="completed">Completed</option>
              </select>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="mt-6 flex justify-end space-x-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300 focus:outline-none"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-blue-500 text-white font-semibold rounded-md hover:bg-blue-600 focus:outline-none"
            >
              Create Job
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateJobModal;
