# Use the official PostgreSQL image
FROM postgres:15

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=daniel
ENV POSTGRES_DB=authDB

# Expose the default PostgreSQL port
EXPOSE 5432